language: python
python:
  - "3.6"

script:
  - coverage run testSudoku.py
  - coverage run testInterface.py
  - coverage run testApi.py

install:
  - pip install -r requirements.txt

after_success:
  - coveralls
